apiVersion: v2
name: k8s-common
version: 1.1.3
description: A Library Helm Chart for grouping common logic between charts. This
  chart is not deployable by itself.
type: library
keywords:
  - common
  - helper
  - template
  - function
home: https://next-gen-infrastructure.github.io/kubernetes-helm-charts
sources:
  - https://github.com/next-gen-infrastructure/kubernetes-helm-charts/tree/main/charts/k8s-common
maintainers:
  - name: Alexander Dobrodey
    url: https://github.com/ADobrodey
annotations:
  category: Infrastructure
