apiVersion: v2
name: daemonset
version: 1.1.2
description: Typical Daemon Set application
type: application
dependencies:
  - name: k8s-common
    version: ^1.0.0
    repository: "file://../k8s-common"
home: https://next-gen-infrastructure.github.io/kubernetes-helm-charts
sources:
  - https://github.com/next-gen-infrastructure/kubernetes-helm-charts/tree/main/charts/daemonset
