apiVersion: v2
name: cronjobs
version: 1.1.3
description: Kubernetes Cron Jobs
type: application
dependencies:
  - name: k8s-common
    version: ^1.0.0
    repository: "file://../k8s-common"
sources:
  - https://github.com/next-gen-infrastructure/kubernetes-helm-charts/tree/main/charts/cronjobs
maintainers:
  - name: Alexander Dobrodey
    url: https://github.com/ADobrodey
