{{- if .Values.rbac.create }}
{{- if .Values.rbac.rules }}
---
apiVersion: {{ include "k8s-common.capabilities.rbac.apiVersion" . }}
kind: Role
metadata:
  name: {{ template "k8s-common.names.fullname" . }}
  namespace: {{ include "k8s-common.names.namespace" . | quote }}
  labels: {{- include "k8s-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "k8s-common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
rules:
  {{- include "k8s-common.tplvalues.render" ( dict "value" .Values.rbac.rules "context" $ ) | nindent 2 }}
{{- end }}
{{- end }}
