apiVersion: v2
name: statefulset
version: 1.1.9
description: Typical StateFul Set application
type: application
dependencies:
  - name: k8s-common
    version: ^1.0.0
    repository: "file://../k8s-common"
home: https://next-gen-infrastructure.github.io/kubernetes-helm-charts
sources:
  - https://github.com/next-gen-infrastructure/kubernetes-helm-charts/tree/main/charts/statefulset
maintainers:
  - name: Alexander Dobrodey
    url: https://github.com/ADobrodey
