apiVersion: v2
name: deployment
version: 1.1.11
description: Typical microservice chart. Supports Ingress controller,
  horizontal-scalable containers
type: application
dependencies:
  - name: k8s-common
    version: ^1.0.0
    repository: "file://../k8s-common"
home: https://next-gen-infrastructure.github.io/kubernetes-helm-charts
sources:
  - https://github.com/next-gen-infrastructure/kubernetes-helm-charts/tree/main/charts/deployment
maintainers:
  - name: Alexander Dobrodey
    url: https://github.com/ADobrodey
